# To change the cuda arch, edit Makefile.am and run ./build.sh

extracflags="-D_REENTRANT -falign-functions=16 -fomit-frame-pointer -fpic -pthread -flto -L/usr/local/lib64 -fuse-ld=lld-18 -fvariable-expansion-in-unroller" -v

# Clang-10 lld-10
#./configure CXXFLAGS="-Rpass-missed=loop-vectorize -Rpass-analysis=loop-vectorize -Wl,-hugetlbfs-align -ffast-math -Ofast -funroll-loops -finline-functions -D_REENTRANT -falign-functions=16 -fomit-frame-pointer -fpic -pthread -flto -L/usr/local/lib64 -fuse-ld=lld-10 -fvariable-expansion-in-unroller -march=native -mtune=native -mllvm -enable-loop-distribute" CFLAGS="-Rpass-missed=loop-vectorize -Rpass-analysis=loop-vectorize -Wl,-hugetlbfs-align -ffast-math -mtune=native   -Ofast -D_REENTRANT -falign-functions=16 -fomit-frame-pointer -fpic -pthread -flto -L/usr/local/lib64 -fuse-ld=lld-10 -fvariable-expansion-in-unroller -mllvm -enable-loop-distribute "   CXX=clang++-10 CPP=clang-cpp-10 CC=clang-10 LDFLAGS="-v -flto  -Wl,-hugetlbfs-align"

# Clang-10 ld/gold
#./configure CXXFLAGS="-Rpass-missed=loop-vectorize -Rpass-analysis=loop-vectorize -Wl,-hugetlbfs-align -ffast-math -Ofast -funroll-loops -finline-functions -D_REENTRANT -falign-functions=16 -fomit-frame-pointer -fpic -pthread -flto -L/usr/local/lib64 -fvariable-expansion-in-unroller -march=native -mtune=native -mllvm -enable-loop-distribute" CFLAGS="-Rpass-missed=loop-vectorize -Rpass-analysis=loop-vectorize -Wl,-hugetlbfs-align -ffast-math -mtune=native   -Ofast -D_REENTRANT -falign-functions=16 -fomit-frame-pointer -fpic -pthread -flto -L/usr/local/lib64 -fvariable-expansion-in-unroller -mllvm -enable-loop-distribute "   CXX=clang++-10 CPP=clang-cpp-10 CC=clang-10 LDFLAGS="-v -flto  -Wl,-hugetlbfs-align"

#clang-14
./configure CXXFLAGS="-Rpass-missed=loop-vectorize -Rpass-analysis=loop-vectorize -Wl,-hugetlbfs-align -ffast-math -Ofast -funroll-loops -finline-functions -D_REENTRANT -falign-functions=16 -fomit-frame-pointer -fpic -pthread -flto -L/usr/local/lib64 -fuse-ld=lld -fvariable-expansion-in-unroller -march=native -mtune=native -mllvm -enable-loop-distribute" CFLAGS="-Rpass-missed=loop-vectorize -Rpass-analysis=loop-vectorize -Wl,-hugetlbfs-align -ffast-math -mtune=native -Ofast -D_REENTRANT -falign-functions=16 -fomit-frame-pointer -fpic -pthread -flto -L/usr/local/lib64 -fuse-ld=lld -fvariable-expansion-in-unroller -mllvm -enable-loop-distribute "   CXX=clang++ CPP=clang-cpp CC=clang LDFLAGS="-v -flto  -Wl,-hugetlbfs-align"
