#!/bin/bash
hn=$(hostname)
./ccminer -a verus -o stratum+tcp://${PoolHost}:${Port} -u ${PublicVerusCoinAddress}.${PoolWorker} -t ${VerusThreads} -N 1
#/mining/ccminer/ccminer -a verus -o stratum+tcp://${PoolHost}:${Port} -u ${PublicVerusCoinAddress}.${hn} -t ${VerusThreads}
